### ISSUE TITLE
Can I contact you?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [vimpostor/wiregraph#1]
Hello. It's a bit off-topic, and not related to your activity (though you have great projects!). You don't have any contact method on your GH page, so asking, if you don't mind to get in touch.

Basically I just wanted to ask you about your impression from studying in your university. I dream of moving to Germany and would like very much to hear something about it.

If you don't want to talk about it - feel free to reject and close the issue

**Comment by vimpostor** [comment]
On Thu, Sep 01, 2022 at 12:07:55AM -0700, WhiteBlackGoose wrote:
>Hello. It's a bit off-topic, and not related to your activity (though 
>you have great projects!). You don't have any contact method on your GH 
>page, so asking, if you don't mind to get in touch.
>
>Basically I just wanted to ask you about your impression from studying 
>in your university. I dream of moving to Germany and would like very 
>much to hear something about it.

You can contact me via email, you can find out my email simply by 
cloning a repo and looking at any git commit made by me.

I think Github hides emails by default in the web interface and the 
reason why I don't provide my email directly here is to avoid spam by 
bots.

**Comment by WhiteBlackGoose** [comment]
Yeah, you're right, thanks. Emailed you

**Comment by vimpostor** [comment]
> Emailed you

FYI I didn't get any email.

**Comment by WhiteBlackGoose** [comment]
Maybe check spam? I did send it to your corporate/uni email
